def get_team_names(team_code):
    team_data = team_code_to_team_name.get(team_code.lower())
    return team_data if team_data else team_code

def get_country_codes(nationality):
    country_data = nationality_to_country.get(nationality.lower())
    return country_data.get("alpha2"), country_data.get("alpha3")


# Dictionary maps

team_code_to_team_name = {
    "mercedes": "Mercedes",
    "ferrari": "Ferrari",
    "red_bull": "Red Bull Racing",
    "mclaren": "McLaren",
    "alpine": "Alpine",
    "williams": "Williams",
    "aston_martin": "Aston Martin",
    "rb": "Racing Bulls",
    "sauber": "Kick Sauber",
    "haas": "Haas",
}

nationality_to_country = {
    "andorran": {"alpha2": "AD", "alpha3": "AND", "country": "Andorra"},
    "emirati": {"alpha2": "AE", "alpha3": "ARE", "country": "United Arab Emirates"},
    "afghan": {"alpha2": "AF", "alpha3": "AFG", "country": "Afghanistan"},
    "antiguan": {"alpha2": "AG", "alpha3": "ATG", "country": "Antigua and Barbuda"},
    "barbudan": {"alpha2": "AG", "alpha3": "ATG", "country": "Antigua and Barbuda"},
    "anguillian": {"alpha2": "AI", "alpha3": "AIA", "country": "Anguilla"},
    "albanian": {"alpha2": "AL", "alpha3": "ALB", "country": "Albania"},
    "armenian": {"alpha2": "AM", "alpha3": "ARM", "country": "Armenia"},
    "dutch": {"alpha2": "AN", "alpha3": "ANT", "country": "Netherlands Antilles"},
    "angolan": {"alpha2": "AO", "alpha3": "AGO", "country": "Angola"},
    "argentine": {"alpha2": "AR", "alpha3": "ARG", "country": "Argentina"},
    "american samoan": {"alpha2": "AS", "alpha3": "ASM", "country": "American Samoa"},
    "austrian": {"alpha2": "AT", "alpha3": "AUT", "country": "Austria"},
    "australian": {"alpha2": "AU", "alpha3": "AUS", "country": "Australia"},
    "aruban": {"alpha2": "AW", "alpha3": "ABW", "country": "Aruba"},
    "swedish": {"alpha2": "AX", "alpha3": "ALA", "country": "Åland Islands"},
    "azerbaijani": {"alpha2": "AZ", "alpha3": "AZE", "country": "Azerbaijan"},
    "bosnian": {"alpha2": "BA", "alpha3": "BIH", "country": "Bosnia and Herzegovina"},
    "herzegovinian": {"alpha2": "BA", "alpha3": "BIH", "country": "Bosnia and Herzegovina"},
    "barbadian": {"alpha2": "BB", "alpha3": "BRB", "country": "Barbados"},
    "bangladeshi": {"alpha2": "BD", "alpha3": "BGD", "country": "Bangladesh"},
    "belgian": {"alpha2": "BE", "alpha3": "BEL", "country": "Belgium"},
    "burkinabe": {"alpha2": "BF", "alpha3": "BFA", "country": "Burkina Faso"},
    "bulgarian": {"alpha2": "BG", "alpha3": "BGR", "country": "Bulgaria"},
    "bahraini": {"alpha2": "BH", "alpha3": "BHR", "country": "Bahrain"},
    "burundian": {"alpha2": "BI", "alpha3": "BDI", "country": "Burundi"},
    "beninese": {"alpha2": "BJ", "alpha3": "BEN", "country": "Benin"},
    "saint barthélemy islander": {"alpha2": "BL", "alpha3": "BLM", "country": "Saint Barthélemy"},
    "bermudian": {"alpha2": "BM", "alpha3": "BMU", "country": "Bermuda"},
    "bruneian": {"alpha2": "BN", "alpha3": "BRN", "country": "Brunei"},
    "bolivian": {"alpha2": "BO", "alpha3": "BOL", "country": "Bolivia"},
    "brazilian": {"alpha2": "BR", "alpha3": "BRA", "country": "Brazil"},
    "bahamian": {"alpha2": "BS", "alpha3": "BHS", "country": "Bahamas"},
    "bhutanese": {"alpha2": "BT", "alpha3": "BTN", "country": "Bhutan"},
    "motswana": {"alpha2": "BW", "alpha3": "BWA", "country": "Botswana"},
    "belarusian": {"alpha2": "BY", "alpha3": "BLR", "country": "Belarus"},
    "belizean": {"alpha2": "BZ", "alpha3": "BLZ", "country": "Belize"},
    "canadian": {"alpha2": "CA", "alpha3": "CAN", "country": "Canada"},
    "cocos islander": {"alpha2": "CC", "alpha3": "CCK", "country": "Cocos [Keeling] Islands"},
    "congolese": {"alpha2": "CD", "alpha3": "COD", "country": "Congo - Kinshasa"},
    "central african": {"alpha2": "CF", "alpha3": "CAF", "country": "Central African Republic"},
    "swiss": {"alpha2": "CH", "alpha3": "CHE", "country": "Switzerland"},
    "ivorian": {"alpha2": "CI", "alpha3": "CIV", "country": "Côte d'Ivoire"},
    "cook islander": {"alpha2": "CK", "alpha3": "COK", "country": "Cook Islands"},
    "chilean": {"alpha2": "CL", "alpha3": "CHL", "country": "Chile"},
    "cameroonian": {"alpha2": "CM", "alpha3": "CMR", "country": "Cameroon"},
    "chinese": {"alpha2": "CN", "alpha3": "CHN", "country": "China"},
    "colombian": {"alpha2": "CO", "alpha3": "COL", "country": "Colombia"},
    "costa rican": {"alpha2": "CR", "alpha3": "CRI", "country": "Costa Rica"},
    "montenegrins": {"alpha2": "CS", "alpha3": "SCG", "country": "Serbia and Montenegro"},
    "serbs": {"alpha2": "CS", "alpha3": "SCG", "country": "Serbia and Montenegro"},
    "cuban": {"alpha2": "CU", "alpha3": "CUB", "country": "Cuba"},
    "cape verdian": {"alpha2": "CV", "alpha3": "CPV", "country": "Cape Verde"},
    "curaçaoan": {"alpha2": "CW", "alpha3": "CUW", "country": "Curaçao"},
    "christmas island": {"alpha2": "CX", "alpha3": "CXR", "country": "Christmas Island"},
    "cypriot": {"alpha2": "CY", "alpha3": "CYP", "country": "Cyprus"},
    "czech": {"alpha2": "CZ", "alpha3": "CZE", "country": "Czech Republic"},
    "german": {"alpha2": "DE", "alpha3": "DEU", "country": "Germany"},
    "djibouti": {"alpha2": "DJ", "alpha3": "DJI", "country": "Djibouti"},
    "danish": {"alpha2": "DK", "alpha3": "DNK", "country": "Denmark"},
    "dominican": {"alpha2": "DM", "alpha3": "DMA", "country": "Dominica"},
    "algerian": {"alpha2": "DZ", "alpha3": "DZA", "country": "Algeria"},
    "ecuadorean": {"alpha2": "EC", "alpha3": "ECU", "country": "Ecuador"},
    "estonian": {"alpha2": "EE", "alpha3": "EST", "country": "Estonia"},
    "egyptian": {"alpha2": "EG", "alpha3": "EGY", "country": "Egypt"},
    "sahrawi": {"alpha2": "EH", "alpha3": "ESH", "country": "Western Sahara"},
    "eritrean": {"alpha2": "ER", "alpha3": "ERI", "country": "Eritrea"},
    "spanish": {"alpha2": "ES", "alpha3": "ESP", "country": "Spain"},
    "ethiopian": {"alpha2": "ET", "alpha3": "ETH", "country": "Ethiopia"},
    "finnish": {"alpha2": "FI", "alpha3": "FIN", "country": "Finland"},
    "fijian": {"alpha2": "FJ", "alpha3": "FJI", "country": "Fiji"},
    "falkland islander": {"alpha2": "FK", "alpha3": "FLK", "country": "Falkland Islands"},
    "micronesian": {"alpha2": "FM", "alpha3": "FSM", "country": "Micronesia"},
    "faroese": {"alpha2": "FO", "alpha3": "FRO", "country": "Faroe Islands"},
    "french": {"alpha2": "FR", "alpha3": "FRA", "country": "France"},
    "gabonese": {"alpha2": "GA", "alpha3": "GAB", "country": "Gabon"},
    "british": {"alpha2": "GB", "alpha3": "GBR", "country": "United Kingdom"},
    "grenadian": {"alpha2": "GD", "alpha3": "GRD", "country": "Grenada"},
    "georgian": {"alpha2": "GE", "alpha3": "GEO", "country": "Georgia"},
    "channel islander": {"alpha2": "GG", "alpha3": "GGY", "country": "Guernsey"},
    "ghanaian": {"alpha2": "GH", "alpha3": "GHA", "country": "Ghana"},
    "gibraltar": {"alpha2": "GI", "alpha3": "GIB", "country": "Gibraltar"},
    "greenlandic": {"alpha2": "GL", "alpha3": "GRL", "country": "Greenland"},
    "gambian": {"alpha2": "GM", "alpha3": "GMB", "country": "Gambia"},
    "guinean": {"alpha2": "GN", "alpha3": "GIN", "country": "Guinea"},
    "guadeloupian": {"alpha2": "GP", "alpha3": "GLP", "country": "Guadeloupe"},
    "equatorial guinean": {"alpha2": "GQ", "alpha3": "GNQ", "country": "Equatorial Guinea"},
    "greek": {"alpha2": "GR", "alpha3": "GRC", "country": "Greece"},
    "south georgia and the south sandwich islander": {"alpha2": "GS", "alpha3": "SGS", "country": "South Georgia and the South Sandwich Islands"},
    "guatemalan": {"alpha2": "GT", "alpha3": "GTM", "country": "Guatemala"},
    "guamanian": {"alpha2": "GU", "alpha3": "GUM", "country": "Guam"},
    "guinea-bissauan": {"alpha2": "GW", "alpha3": "GNB", "country": "Guinea-Bissau"},
    "guyanese": {"alpha2": "GY", "alpha3": "GUY", "country": "Guyana"},
    "heard and mcdonald islander": {"alpha2": "HM", "alpha3": "HMD", "country": "Heard Island and McDonald Islands"},
    "honduran": {"alpha2": "HN", "alpha3": "HND", "country": "Honduras"},
    "croatian": {"alpha2": "HR", "alpha3": "HRV", "country": "Croatia"},
    "haitian": {"alpha2": "HT", "alpha3": "HTI", "country": "Haiti"},
    "hungarian": {"alpha2": "HU", "alpha3": "HUN", "country": "Hungary"},
    "indonesian": {"alpha2": "ID", "alpha3": "IDN", "country": "Indonesia"},
    "irish": {"alpha2": "IE", "alpha3": "IRL", "country": "Ireland"},
    "israeli": {"alpha2": "IL", "alpha3": "ISR", "country": "Israel"},
    "manx": {"alpha2": "IM", "alpha3": "IMN", "country": "Isle of Man"},
    "indian": {"alpha2": "IN", "alpha3": "IND", "country": "India"},
    "iraqi": {"alpha2": "IQ", "alpha3": "IRQ", "country": "Iraq"},
    "iranian": {"alpha2": "IR", "alpha3": "IRN", "country": "Iran"},
    "icelander": {"alpha2": "IS", "alpha3": "ISL", "country": "Iceland"},
    "italian": {"alpha2": "IT", "alpha3": "ITA", "country": "Italy"},
    "jamaican": {"alpha2": "JM", "alpha3": "JAM", "country": "Jamaica"},
    "jordanian": {"alpha2": "JO", "alpha3": "JOR", "country": "Jordan"},
    "japanese": {"alpha2": "JP", "alpha3": "JPN", "country": "Japan"},
    "kenyan": {"alpha2": "KE", "alpha3": "KEN", "country": "Kenya"},
    "kirghiz": {"alpha2": "KG", "alpha3": "KGZ", "country": "Kyrgyzstan"},
    "cambodian": {"alpha2": "KH", "alpha3": "KHM", "country": "Cambodia"},
    "i-kiribati": {"alpha2": "KI", "alpha3": "KIR", "country": "Kiribati"},
    "comoran": {"alpha2": "KM", "alpha3": "COM", "country": "Comoros"},
    "kittian and nevisian": {"alpha2": "KN", "alpha3": "KNA", "country": "Saint Kitts and Nevis"},
    "north korean": {"alpha2": "KP", "alpha3": "PRK", "country": "North Korea"},
    "south korean": {"alpha2": "KR", "alpha3": "KOR", "country": "South Korea"},
    "kuwaiti": {"alpha2": "KW", "alpha3": "KWT", "country": "Kuwait"},
    "caymanian": {"alpha2": "KY", "alpha3": "CYM", "country": "Cayman Islands"},
    "kazakhstani": {"alpha2": "KZ", "alpha3": "KAZ", "country": "Kazakhstan"},
    "laotian": {"alpha2": "LA", "alpha3": "LAO", "country": "Laos"},
    "lebanese": {"alpha2": "LB", "alpha3": "LBN", "country": "Lebanon"},
    "saint lucian": {"alpha2": "LC", "alpha3": "LCA", "country": "Saint Lucia"},
    "liechtensteiner": {"alpha2": "LI", "alpha3": "LIE", "country": "Liechtenstein"},
    "sri lankan": {"alpha2": "LK", "alpha3": "LKA", "country": "Sri Lanka"},
    "liberian": {"alpha2": "LR", "alpha3": "LBR", "country": "Liberia"},
    "mosotho": {"alpha2": "LS", "alpha3": "LSO", "country": "Lesotho"},
    "lithuanian": {"alpha2": "LT", "alpha3": "LTU", "country": "Lithuania"},
    "luxembourger": {"alpha2": "LU", "alpha3": "LUX", "country": "Luxembourg"},
    "latvian": {"alpha2": "LV", "alpha3": "LVA", "country": "Latvia"},
    "libyan": {"alpha2": "LY", "alpha3": "LBY", "country": "Libya"},
    "moroccan": {"alpha2": "MA", "alpha3": "MAR", "country": "Morocco"},
    "monegasque": {"alpha2": "MC", "alpha3": "MCO", "country": "Monaco"},
    "moldovan": {"alpha2": "MD", "alpha3": "MDA", "country": "Moldova"},
    "montenegrin": {"alpha2": "ME", "alpha3": "MNE", "country": "Montenegro"},
    "saint martin islander": {"alpha2": "MF", "alpha3": "MAF", "country": "Saint Martin"},
    "malagasy": {"alpha2": "MG", "alpha3": "MDG", "country": "Madagascar"},
    "marshallese": {"alpha2": "MH", "alpha3": "MHL", "country": "Marshall Islands"},
    "macedonian": {"alpha2": "MK", "alpha3": "MKD", "country": "Macedonia"},
    "malian": {"alpha2": "ML", "alpha3": "MLI", "country": "Mali"},
    "myanmar": {"alpha2": "MM", "alpha3": "MMR", "country": "Myanmar [Burma]"},
    "mongolian": {"alpha2": "MN", "alpha3": "MNG", "country": "Mongolia"},
    "american": {"alpha2": "MP", "alpha3": "MNP", "country": "Northern Mariana Islands"},
    "mauritanian": {"alpha2": "MR", "alpha3": "MRT", "country": "Mauritania"},
    "montserratian": {"alpha2": "MS", "alpha3": "MSR", "country": "Montserrat"},
    "maltese": {"alpha2": "MT", "alpha3": "MLT", "country": "Malta"},
    "mauritian": {"alpha2": "MU", "alpha3": "MUS", "country": "Mauritius"},
    "maldivan": {"alpha2": "MV", "alpha3": "MDV", "country": "Maldives"},
    "malawian": {"alpha2": "MW", "alpha3": "MWI", "country": "Malawi"},
    "mexican": {"alpha2": "MX", "alpha3": "MEX", "country": "Mexico"},
    "malaysian": {"alpha2": "MY", "alpha3": "MYS", "country": "Malaysia"},
    "mozambican": {"alpha2": "MZ", "alpha3": "MOZ", "country": "Mozambique"},
    "namibian": {"alpha2": "NA", "alpha3": "NAM", "country": "Namibia"},
    "new caledonian": {"alpha2": "NC", "alpha3": "NCL", "country": "New Caledonia"},
    "nigerian": {"alpha2": "NE", "alpha3": "NER", "country": "Niger"},
    "norfolk islander": {"alpha2": "NF", "alpha3": "NFK", "country": "Norfolk Island"},
    "niuean": {"alpha2": "NU", "alpha3": "NIU", "country": "Niue"},
    "new zealander": {"alpha2": "NZ", "alpha3": "NZL", "country": "New Zealand"},
    "omani": {"alpha2": "OM", "alpha3": "OMN", "country": "Oman"},
    "panamanian": {"alpha2": "PA", "alpha3": "PAN", "country": "Panama"},
    "peruvian": {"alpha2": "PE", "alpha3": "PER", "country": "Peru"},
    "french polynesian": {"alpha2": "PF", "alpha3": "PYF", "country": "French Polynesia"},
    "papua new guinean": {"alpha2": "PG", "alpha3": "PNG", "country": "Papua New Guinea"},
    "filipino": {"alpha2": "PH", "alpha3": "PHL", "country": "Philippines"},
    "pakistani": {"alpha2": "PK", "alpha3": "PAK", "country": "Pakistan"},
    "polish": {"alpha2": "PL", "alpha3": "POL", "country": "Poland"},
    "pitcairn islander": {"alpha2": "PN", "alpha3": "PCN", "country": "Pitcairn Islands"},
    "puerto rican": {"alpha2": "PR", "alpha3": "PRI", "country": "Puerto Rico"},
    "palestinian": {"alpha2": "PS", "alpha3": "PSE", "country": "Palestinian Territories"},
    "portuguese": {"alpha2": "PT", "alpha3": "PRT", "country": "Portugal"},
    "palauan": {"alpha2": "PW", "alpha3": "PLW", "country": "Palau"},
    "paraguayan": {"alpha2": "PY", "alpha3": "PRY", "country": "Paraguay"},
    "qatari": {"alpha2": "QA", "alpha3": "QAT", "country": "Qatar"},
    "romanian": {"alpha2": "RO", "alpha3": "ROU", "country": "Romania"},
    "serbian": {"alpha2": "RS", "alpha3": "SRB", "country": "Serbia"},
    "russian": {"alpha2": "RU", "alpha3": "RUS", "country": "Russia"},
    "rwandan": {"alpha2": "RW", "alpha3": "RWA", "country": "Rwanda"},
    "saudi arabian": {"alpha2": "SA", "alpha3": "SAU", "country": "Saudi Arabia"},
    "solomon islander": {"alpha2": "SB", "alpha3": "SLB", "country": "Solomon Islands"},
    "seychellois": {"alpha2": "SC", "alpha3": "SYC", "country": "Seychelles"},
    "sudanese": {"alpha2": "SD", "alpha3": "SDN", "country": "Sudan"},
    "swedish": {"alpha2": "SE", "alpha3": "SWE", "country": "Sweden"},
    "singaporean": {"alpha2": "SG", "alpha3": "SGP", "country": "Singapore"},
    "saint helenian": {"alpha2": "SH", "alpha3": "SHN", "country": "Saint Helena"},
    "slovene": {"alpha2": "SI", "alpha3": "SVN", "country": "Slovenia"},
    "slovak": {"alpha2": "SK", "alpha3": "SVK", "country": "Slovakia"},
    "sierra leonean": {"alpha2": "SL", "alpha3": "SLE", "country": "Sierra Leone"},
    "sammarinese": {"alpha2": "SM", "alpha3": "SMR", "country": "San Marino"},
    "senegalese": {"alpha2": "SN", "alpha3": "SEN", "country": "Senegal"},
    "somali": {"alpha2": "SO", "alpha3": "SOM", "country": "Somalia"},
    "surinamer": {"alpha2": "SR", "alpha3": "SUR", "country": "Suriname"},
    "sao tomean": {"alpha2": "ST", "alpha3": "STP", "country": "São Tomé and Príncipe"},
    "salvadoran": {"alpha2": "SV", "alpha3": "SLV", "country": "El Salvador"},
    "syrian": {"alpha2": "SY", "alpha3": "SYR", "country": "Syria"},
    "swazi": {"alpha2": "SZ", "alpha3": "SWZ", "country": "Swaziland"},
    "turks and caicos islander": {"alpha2": "TC", "alpha3": "TCA", "country": "Turks and Caicos Islands"},
    "chadian": {"alpha2": "TD", "alpha3": "TCD", "country": "Chad"},
    "togolese": {"alpha2": "TG", "alpha3": "TGO", "country": "Togo"},
    "thai": {"alpha2": "TH", "alpha3": "THA", "country": "Thailand"},
    "tadzhik": {"alpha2": "TJ", "alpha3": "TJK", "country": "Tajikistan"},
    "tokelauan": {"alpha2": "TK", "alpha3": "TKL", "country": "Tokelau"},
    "east timorese": {"alpha2": "TL", "alpha3": "TLS", "country": "Timor-Leste"},
    "turkmen": {"alpha2": "TM", "alpha3": "TKM", "country": "Turkmenistan"},
    "tunisian": {"alpha2": "TN", "alpha3": "TUN", "country": "Tunisia"},
    "tongan": {"alpha2": "TO", "alpha3": "TON", "country": "Tonga"},
    "turkish": {"alpha2": "TR", "alpha3": "TUR", "country": "Turkey"},
    "trinidadian": {"alpha2": "TT", "alpha3": "TTO", "country": "Trinidad and Tobago"},
    "tuvaluan": {"alpha2": "TV", "alpha3": "TUV", "country": "Tuvalu"},
    "taiwanese": {"alpha2": "TW", "alpha3": "TWN", "country": "Taiwan"},
    "tanzanian": {"alpha2": "TZ", "alpha3": "TZA", "country": "Tanzania"},
    "ukrainian": {"alpha2": "UA", "alpha3": "UKR", "country": "Ukraine"},
    "ugandan": {"alpha2": "UG", "alpha3": "UGA", "country": "Uganda"},
    "american": {"alpha2": "US", "alpha3": "USA", "country": "United States"},
    "uruguayan": {"alpha2": "UY", "alpha3": "URY", "country": "Uruguay"},
    "uzbekistani": {"alpha2": "UZ", "alpha3": "UZB", "country": "Uzbekistan"},
    "venezuelan": {"alpha2": "VE", "alpha3": "VEN", "country": "Venezuela"},
    "virgin islander": {"alpha2": "VG", "alpha3": "VGB", "country": "British Virgin Islands"},
    "vietnamese": {"alpha2": "VN", "alpha3": "VNM", "country": "Vietnam"},
    "ni-vanuatu": {"alpha2": "VU", "alpha3": "VUT", "country": "Vanuatu"},
    "wallis and futuna islander": {"alpha2": "WF", "alpha3": "WLF", "country": "Wallis and Futuna"},
    "samoan": {"alpha2": "WS", "alpha3": "WSM", "country": "Samoa"},
    "yemeni": {"alpha2": "YE", "alpha3": "YEM", "country": "Yemen"},
    "south african": {"alpha2": "ZA", "alpha3": "ZAF", "country": "South Africa"},
    "zambian": {"alpha2": "ZM", "alpha3": "ZMB", "country": "Zambia"},
    "zimbabwean": {"alpha2": "ZW", "alpha3": "ZWE", "country": "Zimbabwe"},

    # Alias and common variations
    "monaguesque": {"alpha2": "MC", "alpha3": "MCO", "country": "Monaco"},
    "spaniard": {"alpha2": "ES", "alpha3": "ESP", "country": "Spain"},
    "american": {"alpha2": "US", "alpha3": "USA", "country": "United States"},
    "burmese": {"alpha2": "MM", "alpha3": "MMR", "country": "Myanmar [Burma]"},
}
