def get_team_names(team_code):
    team_data = team_code_to_team_name.get(team_code.lower())
    return team_data if team_data else team_code

def get_country_codes(nationality):
    country_data = nationality_to_country.get(nationality.lower())
    return country_data.get("alpha2"), country_data.get("alpha3")


# Dictionary maps

team_code_to_team_name = {
    "mercedes": "Mercedes",
    "ferrari": "Ferrari",
    "red_bull": "Red Bull Racing",
    "mclaren": "McLaren",
    "alpine": "Alpine",
    "williams": "Williams",
    "aston_martin": "Aston Martin",
    "rb": "Racing Bulls",
    "sauber": "Kick Sauber",
    "haas": "Haas",
}

nationality_to_country = {
    "afghan": {"alpha2": "AF", "alpha3": "AFG", "country": "Afghanistan"},
    "aland islander": {"alpha2": "AX", "alpha3": "ALA", "country": "Åland Islands"},
    "albanian": {"alpha2": "AL", "alpha3": "ALB", "country": "Albania"},
    "algerian": {"alpha2": "DZ", "alpha3": "DZA", "country": "Algeria"},
    "american samoan": {"alpha2": "AS", "alpha3": "ASM", "country": "American Samoa"},
    "andorran": {"alpha2": "AD", "alpha3": "AND", "country": "Andorra"},
    "angolan": {"alpha2": "AO", "alpha3": "AGO", "country": "Angola"},
    "anguillan": {"alpha2": "AI", "alpha3": "AIA", "country": "Anguilla"},
    "antarctic": {"alpha2": "AQ", "alpha3": "ATA", "country": "Antarctica"},
    "antiguan or barbudan": {"alpha2": "AG", "alpha3": "ATG", "country": "Antigua and Barbuda"},
    "argentine": {"alpha2": "AR", "alpha3": "ARG", "country": "Argentina"},
    "armenian": {"alpha2": "AM", "alpha3": "ARM", "country": "Armenia"},
    "aruban": {"alpha2": "AW", "alpha3": "ABW", "country": "Aruba"},
    "australian": {"alpha2": "AU", "alpha3": "AUS", "country": "Australia"},
    "austrian": {"alpha2": "AT", "alpha3": "AUT", "country": "Austria"},
    "azerbaijani, azeri": {"alpha2": "AZ", "alpha3": "AZE", "country": "Azerbaijan"},
    "bahamian": {"alpha2": "BS", "alpha3": "BHS", "country": "Bahamas"},
    "bahraini": {"alpha2": "BH", "alpha3": "BHR", "country": "Bahrain"},
    "bangladeshi": {"alpha2": "BD", "alpha3": "BGD", "country": "Bangladesh"},
    "barbadian": {"alpha2": "BB", "alpha3": "BRB", "country": "Barbados"},
    "belarusian": {"alpha2": "BY", "alpha3": "BLR", "country": "Belarus"},
    "belgian": {"alpha2": "BE", "alpha3": "BEL", "country": "Belgium"},
    "belizean": {"alpha2": "BZ", "alpha3": "BLZ", "country": "Belize"},
    "beninese, beninois": {"alpha2": "BJ", "alpha3": "BEN", "country": "Benin"},
    "bermudian, bermudan": {"alpha2": "BM", "alpha3": "BMU", "country": "Bermuda"},
    "bhutanese": {"alpha2": "BT", "alpha3": "BTN", "country": "Bhutan"},
    "bolivian": {"alpha2": "BO", "alpha3": "BOL", "country": "Bolivia (Plurinational State of)"},
    "bonaire": {"alpha2": "BQ", "alpha3": "BES", "country": "Bonaire, Sint Eustatius and Saba"},
    "bosnian or herzegovinian": {"alpha2": "BA", "alpha3": "BIH", "country": "Bosnia and Herzegovina"},
    "motswana, botswanan": {"alpha2": "BW", "alpha3": "BWA", "country": "Botswana"},
    "bouvet island": {"alpha2": "BV", "alpha3": "BVT", "country": "Bouvet Island"},
    "brazilian": {"alpha2": "BR", "alpha3": "BRA", "country": "Brazil"},
    "biot": {"alpha2": "IO", "alpha3": "IOT", "country": "British Indian Ocean Territory"},
    "bruneian": {"alpha2": "BN", "alpha3": "BRN", "country": "Brunei Darussalam"},
    "bulgarian": {"alpha2": "BG", "alpha3": "BGR", "country": "Bulgaria"},
    "burkinabé": {"alpha2": "BF", "alpha3": "BFA", "country": "Burkina Faso"},
    "burundian": {"alpha2": "BI", "alpha3": "BDI", "country": "Burundi"},
    "cabo verdean": {"alpha2": "CV", "alpha3": "CPV", "country": "Cabo Verde"},
    "cambodian": {"alpha2": "KH", "alpha3": "KHM", "country": "Cambodia"},
    "cameroonian": {"alpha2": "CM", "alpha3": "CMR", "country": "Cameroon"},
    "canadian": {"alpha2": "CA", "alpha3": "CAN", "country": "Canada"},
    "caymanian": {"alpha2": "KY", "alpha3": "CYM", "country": "Cayman Islands"},
    "central african": {"alpha2": "CF", "alpha3": "CAF", "country": "Central African Republic"},
    "chadian": {"alpha2": "TD", "alpha3": "TCD", "country": "Chad"},
    "chilean": {"alpha2": "CL", "alpha3": "CHL", "country": "Chile"},
    "chinese": {"alpha2": "CN", "alpha3": "CHN", "country": "China"},
    "christmas island": {"alpha2": "CX", "alpha3": "CXR", "country": "Christmas Island"},
    "cocos island": {"alpha2": "CC", "alpha3": "CCK", "country": "Cocos (Keeling) Islands"},
    "colombian": {"alpha2": "CO", "alpha3": "COL", "country": "Colombia"},
    "comoran, comorian": {"alpha2": "KM", "alpha3": "COM", "country": "Comoros"},
    "congolese (republic of the)": {"alpha2": "CG", "alpha3": "COG", "country": "Congo (Republic of the)"},
    "congolese (democratic republic of the)": {"alpha2": "CD", "alpha3": "COD", "country": "Congo (Democratic Republic of the)"},
    "cook island": {"alpha2": "CK", "alpha3": "COK", "country": "Cook Islands"},
    "costa rican": {"alpha2": "CR", "alpha3": "CRI", "country": "Costa Rica"},
    "ivorian": {"alpha2": "CI", "alpha3": "CIV", "country": "Côte d'Ivoire"},
    "croatian": {"alpha2": "HR", "alpha3": "HRV", "country": "Croatia"},
    "cuban": {"alpha2": "CU", "alpha3": "CUB", "country": "Cuba"},
    "curaçaoan": {"alpha2": "CW", "alpha3": "CUW", "country": "Curaçao"},
    "czech": {"alpha2": "CZ", "alpha3": "CZE", "country": "Czech Republic"},
    "danish": {"alpha2": "DK", "alpha3": "DNK", "country": "Denmark"},
    "djiboutian": {"alpha2": "DJ", "alpha3": "DJI", "country": "Djibouti"},
    "dominican (dominica)": {"alpha2": "DM", "alpha3": "DMA", "country": "Dominica"},
    "dominican (dominican republic)": {"alpha2": "DO", "alpha3": "DOM", "country": "Dominican Republic"},
    "ecuadorian": {"alpha2": "EC", "alpha3": "ECU", "country": "Ecuador"},
    "egyptian": {"alpha2": "EG", "alpha3": "EGY", "country": "Egypt"},
    "salvadoran": {"alpha2": "SV", "alpha3": "SLV", "country": "El Salvador"},
    "equatorial guinean, equatoguinean": {"alpha2": "GQ", "alpha3": "GNQ", "country": "Equatorial Guinea"},
    "eritrean": {"alpha2": "ER", "alpha3": "ERI", "country": "Eritrea"},
    "estonian": {"alpha2": "EE", "alpha3": "EST", "country": "Estonia"},
    "ethiopian": {"alpha2": "ET", "alpha3": "ETH", "country": "Ethiopia"},
    "falkland island": {"alpha2": "FK", "alpha3": "FLK", "country": "Falkland Islands (Malvinas)"},
    "faroese": {"alpha2": "FO", "alpha3": "FRO", "country": "Faroe Islands"},
    "fijian": {"alpha2": "FJ", "alpha3": "FJI", "country": "Fiji"},
    "finnish": {"alpha2": "FI", "alpha3": "FIN", "country": "Finland"},
    "french": {"alpha2": "FR", "alpha3": "FRA", "country": "France"},
    "french guianese": {"alpha2": "GF", "alpha3": "GUF", "country": "French Guiana"},
    "french polynesian": {"alpha2": "PF", "alpha3": "PYF", "country": "French Polynesia"},
    "french southern territories": {"alpha2": "TF", "alpha3": "ATF", "country": "French Southern Territories"},
    "gabonese": {"alpha2": "GA", "alpha3": "GAB", "country": "Gabon"},
    "gambian": {"alpha2": "GM", "alpha3": "GMB", "country": "Gambia"},
    "georgian": {"alpha2": "GE", "alpha3": "GEO", "country": "Georgia"},
    "german": {"alpha2": "DE", "alpha3": "DEU", "country": "Germany"},
    "ghanaian": {"alpha2": "GH", "alpha3": "GHA", "country": "Ghana"},
    "gibraltar": {"alpha2": "GI", "alpha3": "GIB", "country": "Gibraltar"},
    "greek, hellenic": {"alpha2": "GR", "alpha3": "GRC", "country": "Greece"},
    "greenlandic": {"alpha2": "GL", "alpha3": "GRL", "country": "Greenland"},
    "grenadian": {"alpha2": "GD", "alpha3": "GRD", "country": "Grenada"},
    "guadeloupian": {"alpha2": "GP", "alpha3": "GLP", "country": "Guadeloupe"},
    "guamanian, guambat": {"alpha2": "GU", "alpha3": "GUM", "country": "Guam"},
    "guatemalan": {"alpha2": "GT", "alpha3": "GTM", "country": "Guatemala"},
    "guernsey": {"alpha2": "GG", "alpha3": "GGY", "country": "Guernsey"},
    "guinean": {"alpha2": "GN", "alpha3": "GIN", "country": "Guinea"},
    "bissau-guinean": {"alpha2": "GW", "alpha3": "GNB", "country": "Guinea-Bissau"},
    "guyanese": {"alpha2": "GY", "alpha3": "GUY", "country": "Guyana"},
    "heard island or mcdonald islands": {"alpha2": "HM", "alpha3": "HMD", "country": "Heard Island and McDonald Islands"},
    "honduran": {"alpha2": "HN", "alpha3": "HND", "country": "Honduras"},
    "hong kong, hong kongese": {"alpha2": "HK", "alpha3": "HKG", "country": "Hong Kong"},
    "hungarian": {"alpha2": "HU", "alpha3": "HUN", "country": "Hungary"},
    "icelander": {"alpha2": "IS", "alpha3": "ISL", "country": "Iceland"},
    "indian": {"alpha2": "IN", "alpha3": "IND", "country": "India"},
    "indonesian": {"alpha2": "ID", "alpha3": "IDN", "country": "Indonesia"},
    "iranian, persian": {"alpha2": "IR", "alpha3": "IRN", "country": "Iran"},
    "iraqi": {"alpha2": "IQ", "alpha3": "IRQ", "country": "Iraq"},
    "irish": {"alpha2": "IE", "alpha3": "IRL", "country": "Ireland"},
    "manx": {"alpha2": "IM", "alpha3": "IMN", "country": "Isle of Man"},
    "israeli": {"alpha2": "IL", "alpha3": "ISR", "country": "Israel"},
    "italian": {"alpha2": "IT", "alpha3": "ITA", "country": "Italy"},
    "jamaican": {"alpha2": "JM", "alpha3": "JAM", "country": "Jamaica"},
    "japanese": {"alpha2": "JP", "alpha3": "JPN", "country": "Japan"},
    "channel island": {"alpha2": "JE", "alpha3": "JEY", "country": "Jersey"},
    "jordanian": {"alpha2": "JO", "alpha3": "JOR", "country": "Jordan"},
    "kazakhstani, kazakh": {"alpha2": "KZ", "alpha3": "KAZ", "country": "Kazakhstan"},
    "kenyan": {"alpha2": "KE", "alpha3": "KEN", "country": "Kenya"},
    "i-kiribati": {"alpha2": "KI", "alpha3": "KIR", "country": "Kiribati"},
    "north korean": {"alpha2": "KP", "alpha3": "PRK", "country": "Korea (Democratic People's Republic of)"},
    "south korean": {"alpha2": "KR", "alpha3": "KOR", "country": "Korea (Republic of)"},
    "kuwaiti": {"alpha2": "KW", "alpha3": "KWT", "country": "Kuwait"},
    "kyrgyzstani, kyrgyz, kirgiz, kirghiz": {"alpha2": "KG", "alpha3": "KGZ", "country": "Kyrgyzstan"},
    "laotian, lao": {"alpha2": "LA", "alpha3": "LAO", "country": "Lao People's Democratic Republic"},
    "latvian": {"alpha2": "LV", "alpha3": "LVA", "country": "Latvia"},
    "lebanese": {"alpha2": "LB", "alpha3": "LBN", "country": "Lebanon"},
    "basotho": {"alpha2": "LS", "alpha3": "LSO", "country": "Lesotho"},
    "liberian": {"alpha2": "LR", "alpha3": "LBR", "country": "Liberia"},
    "libyan": {"alpha2": "LY", "alpha3": "LBY", "country": "Libya"},
    "liechtenstein": {"alpha2": "LI", "alpha3": "LIE", "country": "Liechtenstein"},
    "lithuanian": {"alpha2": "LT", "alpha3": "LTU", "country": "Lithuania"},
    "luxembourger, luxembourgish": {"alpha2": "LU", "alpha3": "LUX", "country": "Luxembourg"},
    "macanese, chinese (macao)": {"alpha2": "MO", "alpha3": "MAC", "country": "Macao"},
    "macedonian": {"alpha2": "MK", "alpha3": "MKD", "country": "Macedonia (the former Yugoslav Republic of)"},
    "malagasy": {"alpha2": "MG", "alpha3": "MDG", "country": "Madagascar"},
    "malawian": {"alpha2": "MW", "alpha3": "MWI", "country": "Malawi"},
    "malaysian": {"alpha2": "MY", "alpha3": "MYS", "country": "Malaysia"},
    "maldivian": {"alpha2": "MV", "alpha3": "MDV", "country": "Maldives"},
    "malian, malinese": {"alpha2": "ML", "alpha3": "MLI", "country": "Mali"},
    "maltese": {"alpha2": "MT", "alpha3": "MLT", "country": "Malta"},
    "marshallese": {"alpha2": "MH", "alpha3": "MHL", "country": "Marshall Islands"},
    "martiniquais, martinican": {"alpha2": "MQ", "alpha3": "MTQ", "country": "Martinique"},
    "mauritanian": {"alpha2": "MR", "alpha3": "MRT", "country": "Mauritania"},
    "mauritian": {"alpha2": "MU", "alpha3": "MUS", "country": "Mauritius"},
    "mayotte (mahoran)": {"alpha2": "YT", "alpha3": "MYT", "country": "Mayotte"},
    "mexican": {"alpha2": "MX", "alpha3": "MEX", "country": "Mexico"},
    "micronesian": {"alpha2": "FM", "alpha3": "FSM", "country": "Micronesia (Federated States of)"},
    "moldovan": {"alpha2": "MD", "alpha3": "MDA", "country": "Moldova (Republic of)"},
    "monegasque": {"alpha2": "MC", "alpha3": "MCO", "country": "Monaco"},
    "mongolian": {"alpha2": "MN", "alpha3": "MNG", "country": "Mongolia"},
    "montenegrin": {"alpha2": "ME", "alpha3": "MNE", "country": "Montenegro"},
    "montserratian": {"alpha2": "MS", "alpha3": "MSR", "country": "Montserrat"},
    "moroccan": {"alpha2": "MA", "alpha3": "MAR", "country": "Morocco"},
    "mozambican": {"alpha2": "MZ", "alpha3": "MOZ", "country": "Mozambique"},
    "burmese": {"alpha2": "MM", "alpha3": "MMR", "country": "Myanmar"},
    "namibian": {"alpha2": "NA", "alpha3": "NAM", "country": "Namibia"},
    "nauruan": {"alpha2": "NR", "alpha3": "NRU", "country": "Nauru"},
    "nepali, nepalese": {"alpha2": "NP", "alpha3": "NPL", "country": "Nepal"},
    "dutch": {"alpha2": "NL", "alpha3": "NLD", "country": "Netherlands"},
    "new caledonian": {"alpha2": "NC", "alpha3": "NCL", "country": "New Caledonia"},
    "new zealander": {"alpha2": "NZ", "alpha3": "NZL", "country": "New Zealand"},
    "nicaraguan": {"alpha2": "NI", "alpha3": "NIC", "country": "Nicaragua"},
    "nigerien": {"alpha2": "NE", "alpha3": "NER", "country": "Niger"},
    "nigerian": {"alpha2": "NG", "alpha3": "NGA", "country": "Nigeria"},
    "niuean": {"alpha2": "NU", "alpha3": "NIU", "country": "Niue"},
    "norfolk island": {"alpha2": "NF", "alpha3": "NFK", "country": "Norfolk Island"},
    "northern marianan": {"alpha2": "MP", "alpha3": "MNP", "country": "Northern Mariana Islands"},
    "norwegian": {"alpha2": "NO", "alpha3": "NOR", "country": "Norway"},
    "omani": {"alpha2": "OM", "alpha3": "OMN", "country": "Oman"},
    "pakistani": {"alpha2": "PK", "alpha3": "PAK", "country": "Pakistan"},
    "palauan": {"alpha2": "PW", "alpha3": "PLW", "country": "Palau"},
    "palestinian": {"alpha2": "PS", "alpha3": "PSE", "country": "Palestine, State of"},
    "panamanian": {"alpha2": "PA", "alpha3": "PAN", "country": "Panama"},
    "papua new guinean, papuan": {"alpha2": "PG", "alpha3": "PNG", "country": "Papua New Guinea"},
    "paraguayan": {"alpha2": "PY", "alpha3": "PRY", "country": "Paraguay"},
    "peruvian": {"alpha2": "PE", "alpha3": "PER", "country": "Peru"},
    "philippine, filipino": {"alpha2": "PH", "alpha3": "PHL", "country": "Philippines"},
    "pitcairn island": {"alpha2": "PN", "alpha3": "PCN", "country": "Pitcairn"},
    "polish": {"alpha2": "PL", "alpha3": "POL", "country": "Poland"},
    "portuguese": {"alpha2": "PT", "alpha3": "PRT", "country": "Portugal"},
    "puerto rican": {"alpha2": "PR", "alpha3": "PRI", "country": "Puerto Rico"},
    "qatari": {"alpha2": "QA", "alpha3": "QAT", "country": "Qatar"},
    "réunionese, réunionnais": {"alpha2": "RE", "alpha3": "REU", "country": "Réunion"},
    "romanian": {"alpha2": "RO", "alpha3": "ROU", "country": "Romania"},
    "russian": {"alpha2": "RU", "alpha3": "RUS", "country": "Russian Federation"},
    "rwandan": {"alpha2": "RW", "alpha3": "RWA", "country": "Rwanda"},
    "barthélemois": {"alpha2": "BL", "alpha3": "BLM", "country": "Saint Barthélemy"},
    "saint helenian": {"alpha2": "SH", "alpha3": "SHN", "country": "Saint Helena, Ascension and Tristan da Cunha"},
    "kittitian or nevisian": {"alpha2": "KN", "alpha3": "KNA", "country": "Saint Kitts and Nevis"},
    "saint lucian": {"alpha2": "LC", "alpha3": "LCA", "country": "Saint Lucia"},
    "saint-martinoise": {"alpha2": "MF", "alpha3": "MAF", "country": "Saint Martin"},
    "saint-pierrais or miquelonnais": {"alpha2": "PM", "alpha3": "SPM", "country": "Saint Pierre and Miquelon"},
    "saint vincentian, vincentian": {"alpha2": "VC", "alpha3": "VCT", "country": "Saint Vincent and the Grenadines"},
    "samoan": {"alpha2": "WS", "alpha3": "WSM", "country": "Samoa"},
    "sammarinese": {"alpha2": "SM", "alpha3": "SMR", "country": "San Marino"},
    "são toméan": {"alpha2": "ST", "alpha3": "STP", "country": "Sao Tome and Principe"},
    "saudi, saudi arabian": {"alpha2": "SA", "alpha3": "SAU", "country": "Saudi Arabia"},
    "senegalese": {"alpha2": "SN", "alpha3": "SEN", "country": "Senegal"},
    "serbian": {"alpha2": "RS", "alpha3": "SRB", "country": "Serbia"},
    "seychellois": {"alpha2": "SC", "alpha3": "SYC", "country": "Seychelles"},
    "sierra leonean": {"alpha2": "SL", "alpha3": "SLE", "country": "Sierra Leone"},
    "singaporean": {"alpha2": "SG", "alpha3": "SGP", "country": "Singapore"},
    "sint maarten": {"alpha2": "SX", "alpha3": "SXM", "country": "Sint Maarten (Dutch part)"},
    "slovak": {"alpha2": "SK", "alpha3": "SVK", "country": "Slovakia"},
    "slovenian, slovene": {"alpha2": "SI", "alpha3": "SVN", "country": "Slovenia"},
    "solomon island": {"alpha2": "SB", "alpha3": "SLB", "country": "Solomon Islands"},
    "somali, somalian": {"alpha2": "SO", "alpha3": "SOM", "country": "Somalia"},
    "south african": {"alpha2": "ZA", "alpha3": "ZAF", "country": "South Africa"},
    "south georgia or south sandwich islands": {"alpha2": "GS", "alpha3": "SGS", "country": "South Georgia and the South Sandwich Islands"},
    "south sudanese": {"alpha2": "SS", "alpha3": "SSD", "country": "South Sudan"},
    "spanish": {"alpha2": "ES", "alpha3": "ESP", "country": "Spain"},
    "sri lankan": {"alpha2": "LK", "alpha3": "LKA", "country": "Sri Lanka"},
    "sudanese": {"alpha2": "SD", "alpha3": "SDN", "country": "Sudan"},
    "surinamese": {"alpha2": "SR", "alpha3": "SUR", "country": "Suriname"},
    "svalbard": {"alpha2": "SJ", "alpha3": "SJM", "country": "Svalbard and Jan Mayen"},
    "swazi": {"alpha2": "SZ", "alpha3": "SWZ", "country": "Swaziland"},
    "swedish": {"alpha2": "SE", "alpha3": "SWE", "country": "Sweden"},
    "swiss": {"alpha2": "CH", "alpha3": "CHE", "country": "Switzerland"},
    "syrian": {"alpha2": "SY", "alpha3": "SYR", "country": "Syrian Arab Republic"},
    "taiwanese, chinese": {"alpha2": "TW", "alpha3": "TWN", "country": "Taiwan, Province of China"},
    "tajikistani": {"alpha2": "TJ", "alpha3": "TJK", "country": "Tajikistan"},
    "tanzanian": {"alpha2": "TZ", "alpha3": "TZA", "country": "Tanzania, United Republic of"},
    "thai": {"alpha2": "TH", "alpha3": "THA", "country": "Thailand"},
    "timorese": {"alpha2": "TL", "alpha3": "TLS", "country": "Timor-Leste"},
    "togolese": {"alpha2": "TG", "alpha3": "TGO", "country": "Togo"},
    "tokelauan": {"alpha2": "TK", "alpha3": "TKL", "country": "Tokelau"},
    "tongan": {"alpha2": "TO", "alpha3": "TON", "country": "Tonga"},
    "trinidadian or tobagonian": {"alpha2": "TT", "alpha3": "TTO", "country": "Trinidad and Tobago"},
    "tunisian": {"alpha2": "TN", "alpha3": "TUN", "country": "Tunisia"},
    "turkish": {"alpha2": "TR", "alpha3": "TUR", "country": "Turkey"},
    "turkmen": {"alpha2": "TM", "alpha3": "TKM", "country": "Turkmenistan"},
    "turks and caicos island": {"alpha2": "TC", "alpha3": "TCA", "country": "Turks and Caicos Islands"},
    "tuvaluan": {"alpha2": "TV", "alpha3": "TUV", "country": "Tuvalu"},
    "ugandan": {"alpha2": "UG", "alpha3": "UGA", "country": "Uganda"},
    "ukrainian": {"alpha2": "UA", "alpha3": "UKR", "country": "Ukraine"},
    "emirati, emiri": {"alpha2": "AE", "alpha3": "ARE", "country": "United Arab Emirates"},
    "british": {"alpha2": "GB", "alpha3": "GBR", "country": "United Kingdom of Great Britain and Northern Ireland"},
    "american": {"alpha2": "US", "alpha3": "USA", "country": "United States of America"},
    "uruguayan": {"alpha2": "UY", "alpha3": "URY", "country": "Uruguay"},
    "uzbekistani, uzbek": {"alpha2": "UZ", "alpha3": "UZB", "country": "Uzbekistan"},
    "ni-vanuatu, vanuatúan": {"alpha2": "VU", "alpha3": "VUT", "country": "Vanuatu"},
    "venezuelan": {"alpha2": "VE", "alpha3": "VEN", "country": "Venezuela (Bolivarian Republic of)"},
    "vietnamese": {"alpha2": "VN", "alpha3": "VNM", "country": "Vietnam"},
    "virgin island (british)": {"alpha2": "VG", "alpha3": "VGB", "country": "Virgin Islands (British)"},
    "u.s. virgin island": {"alpha2": "VI", "alpha3": "VIR", "country": "Virgin Islands (U.S.)"},
    "wallis and futuna, wallisian or futunan": {"alpha2": "WF", "alpha3": "WLF", "country": "Wallis and Futuna"},
    "sahrawi, sahrawian, sahraouian": {"alpha2": "EH", "alpha3": "ESH", "country": "Western Sahara"},
    "yemeni": {"alpha2": "YE", "alpha3": "YEM", "country": "Yemen"},
    "zambian": {"alpha2": "ZM", "alpha3": "ZMB", "country": "Zambia"},
    "zimbabwean": {"alpha2": "ZW", "alpha3": "ZWE", "country": "Zimbabwe"},
}